name: Build and deploy

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/add-cd'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_SIMPLEDOTORG_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SIMPLEDOTORG_ACCESS_TOCKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: simpledotorg/rtsl_exporter:${{ github.sha }}, simpledotorg/rtsl_exporter:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/add-cd'
    steps:
      - uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.7.3
          command: login ${{ secrets.SANDBOX_ARGOCD_ENDPOINT }}
          options: --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.SANDBOX_ARGOCD_PASSWORD }}
      - uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.7.3
          command: app set rtsl-exporter --helm-set image.tag=${{ github.sha }}
      - uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.7.3
          command: app wait rtsl-exporter --timeout 600
